import type { Campaign } from "./types";

export const CAMPAIGNS: Campaign[] = [
  {
    id: "greyholt",
    name: "Greyholt",
    system: "D&D 2024",
    status: "Planning",
    partySize: 4,
    tone: "Dark fantasy folk horror",
    nextSession: "Session 1: The Road Remembers",
    summary: "Dark fantasy horror in a rural borderland built over imperial ruins and old debts.",
    description:
      "Greyholt is a rural horror campaign about inherited debt, village lies, buried imperial machinery, and four characters whose choices change how they understand themselves.",
    themes: ["Folk horror", "Gothic church-state", "Ancient empire ruins", "Inherited debt"],
    members: [
      { id: "cael", name: "Shad", role: "Player", characterName: "Cael Veyr" },
      { id: "bram", name: "Dustin", role: "Player", characterName: "Bram Hallow" },
      { id: "lucien", name: "Matt", role: "Player", characterName: "Lucien Vale" },
      { id: "oren", name: "Omar", role: "Player", characterName: "Oren Sol" },
    ],
    sessions: [
      {
        id: "road-remembers",
        title: "The Road Remembers",
        status: "Draft",
        summary: "The party converges at Greyholt during Tomas Vey's failed burial.",
        notes: {
          prep: "",
          recap: "",
          scenes: "",
          clues: "",
          loot: "",
          unresolvedThreads: "",
        },
      },
      {
        id: "sealed-well",
        title: "The Sealed Well",
        status: "Draft",
        summary: "The first descent toward the Underworks begins beneath a village lie.",
        notes: {
          prep: "",
          recap: "",
          scenes: "",
          clues: "",
          loot: "",
          unresolvedThreads: "",
        },
      },
    ],
    characters: [
      {
        id: "cael-veyr",
        campaignMemberId: "cael",
        name: "Cael Veyr",
        level: 5,
        className: "Druid",
        subclass: "",
        species: "",
        background: "",
        armorClass: 10,
        hitPointMaximum: 38,
        currentHitPoints: 38,
        temporaryHitPoints: 0,
        speed: 30,
        proficiencyBonus: 3,
        passivePerception: 13,
        strength: 10,
        dexterity: 14,
        constitution: 12,
        intelligence: 11,
        wisdom: 16,
        charisma: 10,
        savingThrows: "",
        skillNotes: "",
        concept: "A quiet heir to an old grief, pulled toward the village truths everyone else avoids.",
        notes: "",
      },
      {
        id: "bram-hallow",
        campaignMemberId: "bram",
        name: "Bram Hallow",
        level: 5,
        className: "Artificer",
        subclass: "",
        species: "",
        background: "",
        armorClass: 14,
        hitPointMaximum: 36,
        currentHitPoints: 36,
        temporaryHitPoints: 0,
        speed: 30,
        proficiencyBonus: 3,
        passivePerception: 11,
        strength: 10,
        dexterity: 14,
        constitution: 14,
        intelligence: 16,
        wisdom: 12,
        charisma: 10,
        savingThrows: "",
        skillNotes: "",
        concept: "A bright noise in a dark place, hiding fear behind invention and laughter.",
        notes: "",
      },
      {
        id: "lucien-vale",
        campaignMemberId: "lucien",
        name: "Lucien Vale",
        level: 5,
        className: "Fighter",
        subclass: "",
        species: "",
        background: "",
        armorClass: 16,
        hitPointMaximum: 44,
        currentHitPoints: 44,
        temporaryHitPoints: 0,
        speed: 30,
        proficiencyBonus: 3,
        passivePerception: 10,
        strength: 16,
        dexterity: 12,
        constitution: 14,
        intelligence: 10,
        wisdom: 10,
        charisma: 12,
        savingThrows: "",
        skillNotes: "",
        concept: "A man who performs confidence until a real act of courage asks for him by name.",
        notes: "",
      },
      {
        id: "oren-sol",
        campaignMemberId: "oren",
        name: "Oren Sol",
        level: 5,
        className: "Paladin",
        subclass: "",
        species: "",
        background: "",
        armorClass: 18,
        hitPointMaximum: 42,
        currentHitPoints: 42,
        temporaryHitPoints: 0,
        speed: 30,
        proficiencyBonus: 3,
        passivePerception: 12,
        strength: 16,
        dexterity: 10,
        constitution: 14,
        intelligence: 10,
        wisdom: 12,
        charisma: 16,
        savingThrows: "",
        skillNotes: "",
        concept: "A disciplined soul testing whether faith is truth, armor, or hunger wearing holy words.",
        notes: "",
      },
    ],
  },
];
