import type { Campaign } from "./types";

export const CAMPAIGNS: Campaign[] = [
  {
    id: "greyholt",
    name: "Greyholt",
    system: "D&D 2024",
    status: "Planning",
    partySize: 4,
    tone: "Dark fantasy folk horror",
    nextSession: "Session 1: The Road Remembers",
    summary: "Dark fantasy horror in a rural borderland built over imperial ruins and old debts.",
    description:
      "Greyholt is a rural horror campaign about inherited debt, village lies, buried imperial machinery, and four characters whose choices change how they understand themselves.",
    themes: ["Folk horror", "Gothic church-state", "Ancient empire ruins", "Inherited debt"],
    members: [
      { id: "cael", name: "Shad", role: "Player", characterName: "Cael Veyr" },
      { id: "bram", name: "Dustin", role: "Player", characterName: "Bram Hallow" },
      { id: "lucien", name: "Matt", role: "Player", characterName: "Lucien Vale" },
      { id: "oren", name: "Omar", role: "Player", characterName: "Oren Sol" },
    ],
    sessions: [
      {
        id: "road-remembers",
        title: "The Road Remembers",
        status: "Draft",
        summary: "The party converges at Greyholt during Tomas Vey's failed burial.",
      },
      {
        id: "sealed-well",
        title: "The Sealed Well",
        status: "Draft",
        summary: "The first descent toward the Underworks begins beneath a village lie.",
      },
    ],
    characters: [
      {
        id: "cael-veyr",
        campaignMemberId: "cael",
        name: "Cael Veyr",
        level: 5,
        className: "Druid",
        subclass: "",
        species: "",
        background: "",
        concept: "A quiet heir to an old grief, pulled toward the village truths everyone else avoids.",
        notes: "",
      },
      {
        id: "bram-hallow",
        campaignMemberId: "bram",
        name: "Bram Hallow",
        level: 5,
        className: "Artificer",
        subclass: "",
        species: "",
        background: "",
        concept: "A bright noise in a dark place, hiding fear behind invention and laughter.",
        notes: "",
      },
      {
        id: "lucien-vale",
        campaignMemberId: "lucien",
        name: "Lucien Vale",
        level: 5,
        className: "Fighter",
        subclass: "",
        species: "",
        background: "",
        concept: "A man who performs confidence until a real act of courage asks for him by name.",
        notes: "",
      },
      {
        id: "oren-sol",
        campaignMemberId: "oren",
        name: "Oren Sol",
        level: 5,
        className: "Paladin",
        subclass: "",
        species: "",
        background: "",
        concept: "A disciplined soul testing whether faith is truth, armor, or hunger wearing holy words.",
        notes: "",
      },
    ],
  },
];
